version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "5@lEt&JFD*8N4y^!vNkF"
            ACCEPT_EULA: "Y"